### ISSUE TITLE
Notification template overrides for notifiers

### ISSUE THREAD

**Issue by muenchdo** [argoproj-labs/argocd-notifications#23]
I think it would be a cool feature to be able to define or override notification templates based on the notifier. I'm currently trying to build a webhook notifier where this could then be used to declare the body of an HTTP POST request.

What do you think?

**Comment by alexmt** [comment]
I think this is a good idea. I've done it already to support slack blocks/attachments. The template has have an optional slack field with the `attachements` and `blocks` definitions. https://argoproj-labs.github.io/argocd-notifications/triggers_and_templates/slack/

In the same way, we can add e.g. opsgenie specific field to the notification [data struct](https://github.com/argoproj-labs/argocd-notifications/blob/master/notifiers/notifiers.go#L17) and change opsgenie integration implementation to use that field instead of default title/body.

**Comment by alexmt** [comment]
If we follow that idea I would also move title/body into `email` subfield and keep only `message` field. Every notification service should check for the service-specific field first and fallback to `message` field if the service-specific field is missing.

**Comment by alexmt** [comment]
I think generic webhooks + [notificationType](https://argoproj-labs.github.io/argocd-notifications/triggers_and_templates/#templates) context value in template implements the proposal. @muenchdo , please let me know if I'm missing something.
